# Game Settings
displayMode=1
screenWidth=1920
screenHeight=1080
vsync=0
gridWidth=120
gridHeight=120
cameraScrollSpeed=323.047
cameraEdgeScrollMargin=50
cameraAcceleration=289.844
cameraMaxSpeed=377.083
