# Game Settings
displayMode=1
screenWidth=1920
screenHeight=1080
vsync=0
gridWidth=20
gridHeight=20
cameraScrollSpeed=205.389
cameraEdgeScrollMargin=50
cameraAcceleration=205.945
cameraMaxSpeed=377.083
