# Game Settings
displayMode=1
screenWidth=1920
screenHeight=1080
vsync=0
gridWidth=80
gridHeight=60
cameraScrollSpeed=262.109
cameraEdgeScrollMargin=50
cameraAcceleration=289.844
cameraMaxSpeed=377.083
